export const TIPS: string[] = [
  "You can press Ctrl+Alt+A to add the current tab to a Tab Group from anywhere",
  "You can press Ctrl+Alt+O to quickly open and restore a Tab Group",
  "You can press Ctrl+Alt+1 through Ctrl+Alt+9 to restore your first nine Tab Groups instantly",
  "You can flip the order of those number-key shortcuts with the 'Keybinding Order' setting",
  "You can press Ctrl+Alt+R to remove the current tab from whichever group it's in",
  "You can press Ctrl+Alt+Shift+R to open a quick pick and delete an entire Tab Group",
  "You can press Ctrl+Alt+G to add every open tab to a new or existing Tab Group in one go",
  "You can press Ctrl+Alt+Shift+G to add only the tabs in your current editor split to a group",
  "You can press Ctrl+Alt+N to create a brand-new empty Tab Group",
  "You can press Ctrl+Alt+E to rename a Tab Group via quick pick without leaving the keyboard",
  "You can select a group in the tree and press F2 to rename it inline",
  "You can select a Tab Group and press Delete (or Backspace on Mac) to remove it",
  "You can press Ctrl+Alt+Enter to restore every tab in the selected Tab Group",
  "You can press Ctrl+Alt+S to create a Tab Snapshot, capturing your entire editor layout, including split panes",
  "You can press Ctrl+Alt+Shift+S to update a Tab Snapshot to match your current layout",
  "You can drag a tab from one Tab Group straight into another to move it",
  "You can drag a Tab Group up or down in the list to reorder it",
  "You can drop one Tab Group onto another to nest it as a subgroup",
  "You can drag a tab onto empty space in the panel to spin it into a new group",
  "You can click the close icon in the panel's title bar to close every open editor tab, pinned tabs included",
  "You can use Undo Delete right after removing a group to bring it straight back",
  "You can use Undo Close Editors right after closing all your tabs to restore them",
  "You can export your Tab Groups to a JSON file to back them up or share them",
  "You can import Tab Groups from a JSON file to restore them on another machine",
  "You can filter Tab Groups by name to zero in on the one you need",
  "You can right-click a group and sort its tabs by folder, file type, or name",
  "You can sort all your Tab Groups at once by name or creation time",
  "You can use the Collapse All / Expand All toolbar buttons to tidy up a long list of groups",
  "You can right-click a Tab Group and choose 'Add Sub-Group...' to nest groups without dragging",
  "You can right-click any editor tab and choose 'Add to Tab Group...' to file it away",
  "You can click a tab inside a group to preview it without fully opening it",
  "You can right-click a tab inside a group and choose 'Remove Tab from Tab Group' to remove just that one",
  "You can open the Command Palette (Ctrl+Shift+P, or Cmd+Shift+P on Mac) and type 'Add Current Tab to Group...' to file the active tab into a group without touching the mouse",
  "You can hover any Tab Group and click its 'Add all tabs to Tab Group' icon to dump every currently open tab straight into that group",
  "You can right-click a file (or a multi-selection) in the Explorer and choose 'Add to Tab Group...' to file it away without opening it first",
  "You can turn on 'Auto Close on Restore' to close old tabs automatically when you switch groups",
  "You can turn on 'Automatically remove closed tabs' to keep groups in sync with what's actually open",
  "You can turn on 'Prompt for Group Details' to name and color a group before it's even created",
  "You can choose whether new Tab Groups land at the top or bottom of the list in Settings",
  "You can set a custom folder for Tab Group import/export in the extension settings",
  "You can turn on Tab Group Suggestions so Tabstronaut learns which files you open together",
  "You can turn on AI Group Naming to have your AI provider suggest better names for suggested groups",
  "You can apply or dismiss a suggested group right from the panel with one click",
  "You can open the Command Palette (Ctrl+Shift+P, or Cmd+Shift+P on Mac) and run 'Clear Tab Usage Data' to reset what Tabstronaut has learned about your habits",
  "You can open the Ungrouped Tabs view to see every open tab that hasn't been filed into a group yet",
  "You can give each Tab Group its own color from the Edit Tab Group dialog to spot it at a glance",
  "You can turn off 'Move Tab Group on Tab Change' if you'd rather your groups stayed in a fixed order",
  "You can turn on confirmation prompts before removing groups or closing all your tabs",
  "You can use a Tab Snapshot to save a whole multi-pane debugging layout and bring it back later",
  "You can hover a tab in a group and click its restore icon to open just that one tab",
  "You can search 'Tabstronaut' in Keyboard Shortcuts settings to see, and rebind, every shortcut at once",
  "You can right-click a Tab Group for quick access to restore, sort, edit, and remove it",
  "You can glance at a group's description to see the relative time since it was last touched",
  "You can rely on a Tab Group moving to the top automatically when you add, edit, or remove a tab in it (configurable in Settings)",
  "You can open 'Show More Options' in the toolbar to reach less common actions without cluttering the panel",
  "You can turn off 'Display file paths as Tab descriptions' in Settings if you'd rather see just the file name",
  "You can turn on 'Show confirmation messages' in Settings to get a notification every time a tab is added to a group",
  "You can rely on a Tab Snapshot's saved panes being protected from drag-and-drop, so use 'Update Tab Snapshot' to change them instead",
  "You can move a file into a subgroup and trust Tabstronaut to remove it from the parent group automatically, so it's never listed twice",
];

export function getCurrentTip(): string {
  const hourIndex = Math.floor(Date.now() / 3600000);
  return TIPS[hourIndex % TIPS.length];
}
